# Generated by Django 6.0.3 on 2026-03-28 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='researcher',
            table='researcher_data',
        ),
    ]
